#!/usr/bin/env bash

#warning/usage
if [ -z $1 ];then
	echo "ALL FILES ( be careful with this one. )"
	echo "    USAGE: af ....anything you want to execute on all files in the current folder."
	echo "    eg. af tinify"
	echo "    can also be used in combination with the ALL DIRECTORIES command ad."
	exit 0
fi

#make sure only new lines become array
IFS=$'\n'
#for each file do something ( ignores all desktop.ini files )
for F in `find . -maxdepth 1 -type f ! -name "desktop.ini"`
do
	echo "doing $@ on $F"
	$@ $F
done