#!/usr/bin/env bash
#make sure only new lines become array
IFS=$'\n'
#for each file do something ( ignores all desktop.ini files )
for F in `find . -maxdepth 1 -type f ! -name "desktop.ini"`
do
	echo "doing $@ on $F"
	$@ $F
done