#!/usr/bin/env bash
#make sure only new lines become array
IFS=$'\n'
#for each file do something ( ignores all desktop.ini files )
for F in `find . ! -name "desktop.ini" -maxdepth 1 -type f`
do
	echo "doing $@ on $F"
	$@ $F
done